name: V1_BuildAndDeploy_PythonApp_ToAzureWebApp

on:
  repository_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v1 version
      uses: Azure/appservice-build@v1
      with:
        source-directory: django-app
        platform: python
        platform-version: 3.8

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: TestADeploy
        publish-profile: ${{ secrets.v1PythonSampleApp }}
        package: django-app
